### ISSUE TITLE
`ipsilon-server-install` fails on Fedora Linux 40

### ISSUE THREAD

**Issue by gridhead** [fedora-infra/tiny-stage#62]
I tried stepping up the base image from Fedora Linux 39 to Fedora Linux 40 but the [`auth`](https://github.com/fedora-infra/tiny-stage/blob/main/ansible/auth.yml) VM failed to initialize on the [`install ipsilon` phase](https://github.com/fedora-infra/tiny-stage/blob/main/ansible/roles/ipsilon/tasks/main.yml#L44-L58) of the `ipsilon` role. 

Here are the deets from the `/var/log/ipsilon-install.log` file. 

```
[2024-08-01 02:52:46,848] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/helpers/__pycache__ for class Installer
[2024-08-01 02:52:46,848] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/helpers/__init__.py for class Installer
[2024-08-01 02:52:46,849] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/helpers/common.py for class Installer
[2024-08-01 02:52:46,849] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/helpers/ipa.py for class Installer
[2024-08-01 02:52:46,849] [01/Aug/2024:02:52:46]  Added module ipa as ipa
[2024-08-01 02:52:46,849] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/login/__pycache__ for class Installer
[2024-08-01 02:52:46,849] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/login/__init__.py for class Installer
[2024-08-01 02:52:46,849] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/login/authtest.py for class Installer
[2024-08-01 02:52:46,850] [01/Aug/2024:02:52:46]  Added module authtest as testauth
[2024-08-01 02:52:46,850] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/login/common.py for class Installer
[2024-08-01 02:52:46,850] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/login/authform.py for class Installer
[2024-08-01 02:52:46,850] [01/Aug/2024:02:52:46]  Added module authform as form
[2024-08-01 02:52:46,850] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/login/authgssapi.py for class Installer
[2024-08-01 02:52:46,851] [01/Aug/2024:02:52:46]  Added module authgssapi as gssapi
[2024-08-01 02:52:46,851] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/login/authpam.py for class Installer
[2024-08-01 02:52:46,852] [01/Aug/2024:02:52:46]  Added module authpam as pam
[2024-08-01 02:52:46,852] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/info/__pycache__ for class Installer
[2024-08-01 02:52:46,852] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/info/__init__.py for class Installer
[2024-08-01 02:52:46,853] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/info/common.py for class Installer
[2024-08-01 02:52:46,853] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/info/infonss.py for class Installer
[2024-08-01 02:52:46,853] [01/Aug/2024:02:52:46]  Added module infonss as nss
[2024-08-01 02:52:46,853] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/info/infosssd.py for class Installer
[2024-08-01 02:52:46,859] [01/Aug/2024:02:52:46]  Added module infosssd as sssd
[2024-08-01 02:52:46,860] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/info/infofas.py for class Installer
[2024-08-01 02:52:46,860] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/providers/openid for class Installer
[2024-08-01 02:52:46,860] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/providers/__pycache__ for class Installer
[2024-08-01 02:52:46,860] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/providers/openidp.py for class Installer
[2024-08-01 02:52:46,899] [01/Aug/2024:02:52:46]  Added module openidp as openid
[2024-08-01 02:52:46,899] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/providers/__init__.py for class Installer
[2024-08-01 02:52:46,899] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/providers/common.py for class Installer
[2024-08-01 02:52:46,899] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/providers/openidc for class Installer
[2024-08-01 02:52:46,899] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/providers/openidcp.py for class Installer
[2024-08-01 02:52:46,984] [01/Aug/2024:02:52:46]  Added module openidcp as openidc
[2024-08-01 02:52:46,984] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/providers/saml2 for class Installer
[2024-08-01 02:52:46,984] [01/Aug/2024:02:52:46]  Check module /usr/lib/python3.12/site-packages/ipsilon/providers/saml2idp.py for class Installer
[2024-08-01 02:52:47,007] [01/Aug/2024:02:52:47]  Added module saml2idp as saml2
[2024-08-01 02:52:47,008] [01/Aug/2024:02:52:47]  Check module /usr/lib/python3.12/site-packages/ipsilon/authz/__pycache__ for class Installer
[2024-08-01 02:52:47,008] [01/Aug/2024:02:52:47]  Check module /usr/lib/python3.12/site-packages/ipsilon/authz/__init__.py for class Installer
[2024-08-01 02:52:47,008] [01/Aug/2024:02:52:47]  Check module /usr/lib/python3.12/site-packages/ipsilon/authz/allow.py for class Installer
[2024-08-01 02:52:47,008] [01/Aug/2024:02:52:47]  Added module allow as allow
[2024-08-01 02:52:47,008] [01/Aug/2024:02:52:47]  Check module /usr/lib/python3.12/site-packages/ipsilon/authz/common.py for class Installer
[2024-08-01 02:52:47,008] [01/Aug/2024:02:52:47]  Check module /usr/lib/python3.12/site-packages/ipsilon/authz/deny.py for class Installer
[2024-08-01 02:52:47,008] [01/Aug/2024:02:52:47]  Added module deny as deny
[2024-08-01 02:52:47,008] [01/Aug/2024:02:52:47]  Check module /usr/lib/python3.12/site-packages/ipsilon/authz/spgroup.py for class Installer
[2024-08-01 02:52:47,009] [01/Aug/2024:02:52:47]  Added module spgroup as spgroup
[2024-08-01 02:52:47,011] Installation arguments:
[2024-08-01 02:52:47,011] admin_dburi: None
[2024-08-01 02:52:47,011] admin_user: admin
[2024-08-01 02:52:47,011] authz_allow: yes
[2024-08-01 02:52:47,011] authz_deny: no
[2024-08-01 02:52:47,011] authz_spgroup: no
[2024-08-01 02:52:47,011] authz_spgroup_prefix: None
[2024-08-01 02:52:47,011] authz_spgroup_suffix: None
[2024-08-01 02:52:47,011] az_order: ['allow']
[2024-08-01 02:52:47,011] cleanup_interval: 30
[2024-08-01 02:52:47,011] config_profile: None
[2024-08-01 02:52:47,011] database_url: sqlite:///%(datadir)s/%(dbname)s.sqlite
[2024-08-01 02:52:47,011] form: no
[2024-08-01 02:52:47,011] form_service: ipsilon
[2024-08-01 02:52:47,011] gssapi: yes
[2024-08-01 02:52:47,011] gssapi_httpd_keytab: /etc/httpd/conf/ipsilon.keytab
[2024-08-01 02:52:47,011] hostname: auth.tinystage.test
[2024-08-01 02:52:47,011] info_nss: no
[2024-08-01 02:52:47,011] info_sssd: yes
[2024-08-01 02:52:47,011] info_sssd_domain: None
[2024-08-01 02:52:47,011] instance: idp
[2024-08-01 02:52:47,011] ipa: yes
[2024-08-01 02:52:47,011] lm_order: ['gssapi', 'pam']
[2024-08-01 02:52:47,011] openid: yes
[2024-08-01 02:52:47,011] openid_dburi: None
[2024-08-01 02:52:47,011] openid_extensions:
[2024-08-01 02:52:47,011] openidc: yes
[2024-08-01 02:52:47,011] openidc_dburi: None
[2024-08-01 02:52:47,011] openidc_default_attribute_mapping:
[2024-08-01 02:52:47,011] openidc_extensions:
[2024-08-01 02:52:47,011] openidc_static_dburi: None
[2024-08-01 02:52:47,011] openidc_subject_salt: None
[2024-08-01 02:52:47,011] pam: yes
[2024-08-01 02:52:47,011] pam_service: ipsilon
[2024-08-01 02:52:47,011] root_instance: False
[2024-08-01 02:52:47,011] saml2: yes
[2024-08-01 02:52:47,012] saml2_metadata_validity: 1825
[2024-08-01 02:52:47,012] saml2_session_dburl: None
[2024-08-01 02:52:47,012] samlsessions_dburi: None
[2024-08-01 02:52:47,012] secure: no
[2024-08-01 02:52:47,012] server_debugging: True
[2024-08-01 02:52:47,012] session_timeout: 30
[2024-08-01 02:52:47,012] system_user: ipsilon
[2024-08-01 02:52:47,012] testauth: no
[2024-08-01 02:52:47,012] testauth_groups: None
[2024-08-01 02:52:47,012] transaction_dburi: None
[2024-08-01 02:52:47,012] uninstall: False
[2024-08-01 02:52:47,012] users_dburi: None
[2024-08-01 02:52:47,012] yes: False
[2024-08-01 02:52:47,012] Installation initiated
[2024-08-01 02:52:47,012] Installing default config files
[2024-08-01 02:52:47,028] Considering datastore AdminStore
[2024-08-01 02:52:47,028] expected schema argument to be a string, got <class 'sqlalchemy.engine.base.Engine'>.
[2024-08-01 02:52:47,028] expected schema argument to be a string, got <class 'sqlalchemy.engine.base.Engine'>.
Traceback (most recent call last):
  File "/usr/sbin/ipsilon-server-install", line 543, in <module>
    install(fplugins, opts)
  File "/usr/sbin/ipsilon-server-install", line 200, in install
    dbupgrade.execute_upgrade(ipsilon_conf)
  File "/usr/lib/python3.12/site-packages/ipsilon/tools/dbupgrade.py", line 73, in execute_upgrade
    if _upgrade_database(adminstore) not in [True, None]:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ipsilon/tools/dbupgrade.py", line 29, in _upgrade_database
    current_version = datastore._get_schema_version()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ipsilon/util/data.py", line 800, in _get_schema_version
    q = self._query(self._db, 'dbinfo', OPTIONS_TABLE, trans=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ipsilon/util/data.py", line 167, in __init__
    self._table = self._get_table(table, table_def)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ipsilon/util/data.py", line 212, in _get_table
    table = Table(name, MetaData(self._db.engine()), *table_creation)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/sqlalchemy/sql/schema.py", line 5484, in __init__
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: expected schema argument to be a string, got <class 'sqlalchemy.engine.base.Engine'>.
[2024-08-01 02:52:47,034] Installation aborted.
[2024-08-01 02:52:47,034] See log file /var/log/ipsilon-install.log for details
```

I will probably come back to this later once I am done with the Webhook To Fedora Messaging project but for now, I have settled with the Fedora Linux 39-based VMs for the tinystage setup.

**Comment by gridhead** [comment]
The upstream has already been made aware of the issue.

Please see https://pagure.io/ipsilon/issue/404.
